---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxvol
  namespace: default
spec:
  #storageClassName: manual
  accessModes:
    - ReadOnlyMany # so many nodes can mount it, still error with replicas: 3
    #- ReadWriteOnce
  resources:
    requests:
      storage: 1Gi