---
- name: Applies k8s nginx deployment and service
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    # - name: Apply persistent volume definition - nginx
    #   k8s:
    #     state: present
    #     definition: "{{ lookup('file', '../kubernetes/persistent-volume/nginx.yml') }}"

    - name: Apply persistent volume claim definition - nginx
      k8s:
        state: present
        definition: "{{ lookup('file', '../kubernetes/persistent-volume-claims/nginx.yml') }}"

    - name: Apply deployment definition - nginx
      k8s:
        state: present
        definition: "{{ lookup('file', '../kubernetes/deployments/nginx.yml') }}"

    - name: Apply service definition - nginx
      k8s:
        definition: "{{ lookup('file', '../kubernetes/services/nginx.yml') }}"
        state: present